### ISSUE TITLE
Installer: Nothing happens when clicking Next button on Installation Type page ("gpart: No such geom: ada0s1.")

### ISSUE THREAD

**Issue by scootergrisen** [ghostbsd/ghostbsd#10]
Run "sudo gbi" and click Next button 4 times in the installer.
Number 4 time nothing happens.

I get this output in the terminal:

![GhostBSD-20 08 04](https://user-images.githubusercontent.com/1836590/90316562-430d0e80-df23-11ea-9e1c-d76d9bd43538.png)

Don't know if it is the harddrive setup but the installer does not give any information when clicking the Next button.
It least there should be some information in the installer to give the user an idea of what the problem is if e.g. there is no harddrive or whatever the problem might be.

Tested with GhostBSD-20.08.04.iso in VirtualBox version 6.0.14 r133895 (Qt5.6.2) with 40 GB SATA harddrive
Windows 7

Running "gbi --help" does not give me information on how to get the version so i don't know what version it is.

**Comment by unti1x** [comment]
It looks like `gbi` doesn't work if the system already have "linux" partitions (maybe ntfs/fat32/etc too). I think the problem is in a file `gbi/backend-query/disk-label.sh` which returns only 2 elements per line: size and label

**Comment by ericbsd** [comment]
The latest build has the fix https://www.ghostbsd.org/download#latest_builds

**Comment by unti1x** [comment]
I think things like this must be merged into release branch as soon as they fixed because, come on, official installer is not doing what it's supposed to do. I understand that most of users don't really care and can just take the latest instead of release and so on but this is the face of the project and at least it should work unless it's marked unstable. You don't have to be like the "big guys" like Canonical and Mozilla and of course you don't have to listen to a random guy from Github. Just think about it
